app:
  image: rails
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  volumes:
    - .:/app
  working_dir: /app
  ports:
    - '3000:3000'
  links:
    - db
  extends:
    file: .docker-custom.yml
    service: custom
db:
  image: postgres
